CREATE TABLE SALESMAN (
SALESMAN_ID INT PRIMARY KEY NOT NULL,
SNAME VARCHAR(30) NOT NULL,
CITY VARCHAR(30) NOT NULL,
COMMISSION FLOAT NOT NULL
);

INSERT INTO SALESMAN VALUES (5001,"JAMES HOGG","NEW YORK",0.15);
INSERT INTO SALESMAN VALUES (5002,"NAIL KNITE", "PARIS", 0.13);
INSERT INTO SALESMAN VALUES (5005,"PIT ALEX","LONDON",0.11);
INSERT INTO SALESMAN VALUES (5006,"MC LYON","PARIS",0.14);
INSERT INTO SALESMAN VALUES (5007,"PAUL ADAM","ROME",0.13);
INSERT INTO SALESMAN VALUES (5003,"LAUSON HEN","SAN JOSE",0.12);

SELECT * FROM SALESMAN;
SELECT SNAME,COMMISSION FROM SALESMAN;

CREATE TABLE ORDERS(
ORD_NO INT PRIMARY KEY NOT NULL,
PUR_AMT FLOAT NOT NULL,
ORD_DATE DATE NOT NULL,
CUSTOMER_ID INT NOT NULL,
SALESMAN_ID INT NOT NULL
);

INSERT INTO ORDERS VALUES(70001,150.5,"2012-10-05",3005,5002);
SELECT ORD_DATE,SALESMAN_ID,ORD_NO,PUR_AMT FROM ORDERS;