create database Employee;
CREATE TABLE EMPLOYEE (
EMP_ID INT PRIMARY KEY NOT NULL,
EMP_NAME VARCHAR(30) NOT NULL,
JOB_NAME VARCHAR(30) NOT NULL,
MANAGER_ID INT NOT NULL,
HIRE_DATE DATE NOT NULL,
SALARY INT NOT NULL,
DEP_ID INT NOT NULL
);

INSERT INTO EMPLOYEE VALUES (68319,'MR. SINGH','PRESIDENT',
68319,'2011-05-03',600000,1001), (68320, 'MR. ANISH',
'TEAM LEADER',68319,'2023-05-04',150000,1002),(68321, 'MR.NITHIN',
'ASSOCIATE',68319,'2023-05-05',100000,1003), (68322, 'MR. PAKSHI',
'DEVELOPER',68319,'2023-05-06',80000,1004);
SELECT * FROM EMPLOYEE;

-- 1) Find the salaries of all the employees from the “Employee Details” table.
SELECT SALARY FROM EMPLOYEE;

-- 2) Find the unique designations of the employees from the table.
SELECT DISTINCT JOB_NAME FROM EMPLOYEE;

-- 3) Change the salary where the emp_name is “Raj”.
UPDATE EMPLOYEE SET SALARY = "70000" WHERE EMP_NAME = "MR. PAKSHI";

CREATE DATABASE FOOTBALL;

CREATE TABLE FOOTBALL_VENUE (
VENUE_ID INT PRIMARY KEY NOT NULL,
VENUE_NAME VARCHAR(30) NOT NULL,
CITY_ID INT NOT NULL,
CAPACITY INT NOT NULL);

INSERT INTO FOOTBALL_VENUE VALUES (1001,'INDIA',2001,40000),
(1002,'AUSTRALIA',2002,37500), (1003,'SOUTH AFRICA',2003,35000),
(1004,'ENGLAND',2004,32500), (1005,'NEW ZEALAND',2005,30000),
(1006,'SRI LANKA',2006,27000), (1007,'WEST INDIES',2007,25000),
(1008,'PAKISTAN',2008,25000), (1009,'BANGLADESH',2009,22000),
(1010,'AFGHANISTHAM',2010,20000);

SELECT * FROM FOOTBALL_VENUE;

-- 4) Count the number of venues of the football world cup
SELECT COUNT(*) FROM FOOTBALL_VENUE;

-- 5) List all the venue names and capacities in the format of “Location” and “Volume”.
SELECT VENUE_NAME AS LOCATION, CAPACITY AS VOLUME FROM FOOTBALL_VENUE;

-- 6) Delete all the details where venue_name is equal to “Australia” 
DELETE FROM FOOTBALL_VENUE WHERE VENUE_NAME = 'AUSTRALIA';

-- PYTHON CONNECTOR COMMANDS
-- python -m pip install mysqlclient
-- python -m pip install mysql-connector-python
-- python -m pip install pymysql

--					VIEWS

SHOW DATABASES;
SELECT * FROM CUSTOMER; 

-- VIEW IS A VIRTUAL STORAGE AREA/ VIRTUAL TABLE  WHERE WE CAN DO WHATEVER WE WANT 
-- WITHOUT MODIFYING ORIGINAL TABLE
CREATE VIEW SHAKEER AS SELECT * FROM CUSTOMER;
SELECT * FROM SHAKEER;
SELECT * FROM ANISH;

CREATE VIEW ANISH AS SELECT NAME,CITY,SALESMAN_ID FROM CUSTOMER WHERE CITY = 'DELHI';

CREATE INDEX AKRAM  ON CUSTOMER(CITY);
SHOW INDEX FROM CUSTOMER;
SHOW INDEX FROM CUSTOMER WHERE KEY_NAME='AKRAM';

-- python databse connection
-- show databases, show tables, use database_name commands in command line
-- %s can be used to reprsent any type of data in python